weights:
      manifold_norm: 3000.
      manifold_eikonal: 400.
      manifold_div: 0.
      manifold_normals: 0.
      manifold_normal_subspace: 400.
      non_manifold_norm: 200.
      non_manifold_eikonal: 400.
      non_manifold_div: 0.
      neg_hess_norm: 0.
      geodesic: 0.
      cosine: 0.
      orthogonal: 200.
      reconstruction: 0.
params:
      non_manifold_alpha: 10.
      non_manifold_eps: 0.05
      max_hess_norm: 1.
normal_pretraining_batches: 1000