_target_: src.datasets.euclidean.MNIST PCA 2D, CLASSES [3, 9, 0]
normal_estimation_cfg:
  boundary_cfg:
    boundary_neighbor_thr: 0.9
    boundary_sdf_thr: -0.5
  log_sdf_radius: -1.1
  lr: 1
  noise_scale: 0.5
  num_noisy_samples: 5
  optimization_steps: 150
  sdf_level_set: 0
  sdf_loss_weight: 0.9
